# GENERATED FILE - DO NOT EDIT MANUALLY
#
# This file was generated automatically.
# Any manual changes will be overwritten.
#
# Generated by: generator/generate.py
# Source:       generator/emit_events.yaml
# Source:       generator/on_events.yaml

import typing

from pocket_option import models
from pocket_option.client import BasePocketOptionClient

if typing.TYPE_CHECKING:
    from pocket_option.types import JsonValue, NoDataEventListener, TypedEventListener

__all__ = ("PocketOptionClient",)


class PocketOptionClientEmit:
    def __init__(self, client: BasePocketOptionClient) -> None:
        self.client = client

    async def ai_strategy_multi_get_state(self) -> None:
        """Get AI strategy state.

        Category: `ai`
        """

        await self.client.send("ai-strategy-multi/get-state")

    async def change_asset(self, data: models.ChangeAssetRequest) -> None:
        """Changes the active trading asset and timeframe.

        Category: `assets`

        :param data: Asset change request parameters.
        :type data: models.ChangeAssetRequest
        """

        await self.client.send("changeSymbol", data)

    async def subscribe_for_market_sentiment(self, asset: models.Asset) -> None:
        """Subscribes to market sentiment updates for an asset.

        Category: `assets`

        :param asset: Trading asset for sentiment tracking.
        :type asset: models.Asset
        """

        await self.client.send("subfor", asset)

    async def subscribe_to_asset(self, asset: models.Asset) -> None:
        """Subscribes to real-time updates for a trading asset.

        Category: `assets`

        :param asset: Trading asset to subscribe.
        :type asset: models.Asset
        """

        await self.client.send("subscribeSymbol", asset)

    async def unsubscribe_for_market_sentiment(self, asset: models.Asset) -> None:
        """Removes market sentiment subscription for an asset.

        Category: `assets`

        :param asset: Trading asset to remove from sentiment tracking.
        :type asset: models.Asset
        """

        await self.client.send("unsubfor", asset)

    async def unsubscribe_from_asset(self, asset: models.Asset) -> None:
        """Unsubscribes from real-time updates for a trading asset.

        Category: `assets`

        :param asset: Trading asset to unsubscribe from.
        :type asset: models.Asset
        """

        await self.client.send("unSubscribeSymbol", asset)

    async def auth(self, data: models.AuthorizationData) -> None:
        """Authorizes the client session.

        Category: `common`

        :param data: Authorization payload containing session and account information.
        :type data: models.AuthorizationData
        """

        await self.client.send("auth", data)

    async def demo_refill_balance(self) -> None:
        """Refill demo account balance.

        Category: `common`
        """

        await self.client.send("td/refill")

    async def load_history_period(self, data: models.LoadHistoryPeriodRequest) -> None:
        """Requests historical market data for a specific period.

        Category: `common`

        :param data: Historical data request parameters.
        :type data: models.LoadHistoryPeriodRequest
        """

        await self.client.send("loadHistoryPeriod", data)

    async def ps(self) -> None:
        """Sends a heartbeat request to keep the connection alive.

        Category: `common`
        """

        await self.client.send("ps")

    async def update_balance(self) -> None:
        """Request balance update.

        Category: `common`
        """

        await self.client.send("updateBalance")

    async def copy_signal(self, data: models.CopySignalRequest) -> None:
        """Creates a deal from a copy trading signal.

        Category: `deals`

        :param data: Copy signal execution parameters.
        :type data: models.CopySignalRequest
        """

        await self.client.send("copySignalOrder", data)

    async def deals_ai(self) -> None:
        """AI deal operation.

        Category: `deals`
        """

        await self.client.send("deals/ai")

    async def deals_copy(self, data: models.CopyOrderRequest) -> None:
        """Copy existing order

        Category: `deals`

        :param data: None
        :type data: models.CopyOrderRequest
        """

        await self.client.send("copyorder", data)

    async def deals_double_up(self, data: models.DealsDoubleUpRequest) -> None:
        """Double existing deal.

        Category: `deals`

        :param data: None
        :type data: models.DealsDoubleUpRequest
        """

        await self.client.send("deals/double-up", data)

    async def deals_open(self, data: models.OpenDealRequest) -> None:
        """Creates a new trading deal.

        Category: `deals`

        :param data: Deal opening parameters.
        :type data: models.OpenDealRequest
        """

        await self.client.send("openOrder", data)

    async def deals_pending_cancel(self, data: models.CancelPendingDealRequest) -> None:
        """Cancel pending order.

        Category: `deals`

        :param data: None
        :type data: models.CancelPendingDealRequest
        """

        await self.client.send("cancelPendingOrder", data)

    async def deals_pending_open(self, data: models.OpenPendingDealRequest) -> None:
        """Create pending order.

        Category: `deals`

        :param data: None
        :type data: models.OpenPendingDealRequest
        """

        await self.client.send("openPendingOrder", data)

    async def deals_rollover(self, data: models.DealsRolloverRequest) -> None:
        """Rollover existing deal.

        Category: `deals`

        :param data: None
        :type data: models.DealsRolloverRequest
        """

        await self.client.send("deals/rollover", data)

    async def deals_update_opened(self) -> None:
        """No description

        Category: `deals`
        """

        await self.client.send("updateOpenedDeals")

    async def social_disable_only_watched(self) -> None:
        """Disable watched filter.

        Category: `deals`
        """

        await self.client.send("social/disable-only-watched")

    async def social_enable_only_watched(self) -> None:
        """Enable watched filter.

        Category: `deals`
        """

        await self.client.send("social/enable-only-watched")

    async def update_closed_expresses(self) -> None:
        """No description

        Category: `deals`
        """

        await self.client.send("updateClosedExpresses")

    async def indicator_create(self, data: models.IndicatorCreateRequest) -> None:
        """No description

        Category: `indicator`

        :param data: None
        :type data: models.IndicatorCreateRequest
        """

        await self.client.send("indicator/create", data)

    async def indicator_load(self) -> None:
        """Indicates that indicator data has been loaded by the platform.

        Category: `indicator`
        """

        await self.client.send("indicator/load")

    async def signals_stats(self, data: models.SignalsStatsType) -> None:
        """No description

        Category: `signals`

        :param data: None
        :type data: models.SignalsStatsType
        """

        await self.client.send(
            "signals/stats",
            typing.cast(
                "JsonValue",
                models.SignalsStatsTypeAdapter.validate_python(
                    data,
                ),
            ),
        )

    async def signals_subscribe(self) -> None:
        """No description

        Category: `signals`
        """

        await self.client.send("signals/subscribe")

    async def signals_unsubscribe(self) -> None:
        """No description

        Category: `signals`
        """

        await self.client.send("signals/unsubscribe")

    async def favorite_load(self) -> None:
        """Indicates that favorite has been loaded by the platform.

        Category: `ui`
        """

        await self.client.send("favorite/load")

    async def price_alert_add(self, data: models.PriceAlertAddRequest) -> None:
        """No description

        Category: `ui`

        :param data: None
        :type data: models.PriceAlertAddRequest
        """

        await self.client.send("price-alert/add", data)

    async def price_alert_load(self) -> None:
        """Indicates that price alert data has been loaded by the platform.

        Category: `ui`
        """

        await self.client.send("price-alert/load")

    async def price_alert_remove(self, data: models.PriceAlertRemoveRequest) -> None:
        """No description

        Category: `ui`

        :param data: None
        :type data: models.PriceAlertRemoveRequest
        """

        await self.client.send("price-alert/remove", data)


class PocketOptionClientOn:
    def __init__(self, client: BasePocketOptionClient) -> None:
        self.client = client

    @typing.overload
    def assets_update(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateAssetItem]]], None]": ...

    @typing.overload
    def assets_update(
        self,
        handler: "TypedEventListener[list[models.UpdateAssetItem]]",
    ) -> None: ...

    def assets_update(
        self,
        handler: "TypedEventListener[list[models.UpdateAssetItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateAssetItem]]], None] | None":
        """Triggered when available trading assets metadata is updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.UpdateAssetItem]] | None
        """
        return self.client.add_on("updateAssets", handler=handler, model=models.UpdateAssetItemListTypeAdapter)

    @typing.overload
    def change_market_sentiment(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.MarketSentimentItem]]], None]": ...

    @typing.overload
    def change_market_sentiment(
        self,
        handler: "TypedEventListener[list[models.MarketSentimentItem]]",
    ) -> None: ...

    def change_market_sentiment(
        self,
        handler: "TypedEventListener[list[models.MarketSentimentItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.MarketSentimentItem]]], None] | None":
        """Triggered when market sentiment data is updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.MarketSentimentItem]] | None
        """
        return self.client.add_on("chafor", handler=handler, model=models.MarketSentimentItemListTypeAdapter)

    @typing.overload
    def update_close_value(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateCloseValueItem]]], None]": ...

    @typing.overload
    def update_close_value(
        self,
        handler: "TypedEventListener[list[models.UpdateCloseValueItem]]",
    ) -> None: ...

    def update_close_value(
        self,
        handler: "TypedEventListener[list[models.UpdateCloseValueItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateCloseValueItem]]], None] | None":
        """Triggered when real-time price stream values are updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.UpdateCloseValueItem]] | None
        """
        return self.client.add_on("updateStream", handler=handler, model=models.UpdateCloseValueListTypeAdapter)

    @typing.overload
    def update_history_new_fast(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.UpdateHistoryFastEvent]], None]": ...

    @typing.overload
    def update_history_new_fast(
        self,
        handler: "TypedEventListener[models.UpdateHistoryFastEvent]",
    ) -> None: ...

    def update_history_new_fast(
        self,
        handler: "TypedEventListener[models.UpdateHistoryFastEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.UpdateHistoryFastEvent]], None] | None":
        """Triggered when fast historical market data is received.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[models.UpdateHistoryFastEvent] | None
        """
        return self.client.add_on("updateHistoryNewFast", handler=handler, model=models.UpdateHistoryFastEvent)

    @typing.overload
    def balance_success_update(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessUpdateBalanceEvent]], None]": ...

    @typing.overload
    def balance_success_update(
        self,
        handler: "TypedEventListener[models.SuccessUpdateBalanceEvent]",
    ) -> None: ...

    def balance_success_update(
        self,
        handler: "TypedEventListener[models.SuccessUpdateBalanceEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessUpdateBalanceEvent]], None] | None":
        """Triggered when account balance information is updated.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessUpdateBalanceEvent] | None
        """
        return self.client.add_on("successupdateBalance", handler=handler, model=models.SuccessUpdateBalanceEvent)

    @typing.overload
    def connect(
        self,
        handler: None = None,
    ) -> "typing.Callable[[NoDataEventListener], None]": ...

    @typing.overload
    def connect(
        self,
        handler: "NoDataEventListener",
    ) -> None: ...

    def connect(
        self,
        handler: "NoDataEventListener | None" = None,
    ) -> "typing.Callable[[NoDataEventListener], None] | None":
        """Triggered when the Socket.IO connection is established.

        Category: `common`


        :param handler: Callback
        :type handler: NoDataEventListener | None
        """
        return self.client.add_on("connect", handler=handler, model=None)

    @typing.overload
    def disconnect(
        self,
        handler: None = None,
    ) -> "typing.Callable[[NoDataEventListener], None]": ...

    @typing.overload
    def disconnect(
        self,
        handler: "NoDataEventListener",
    ) -> None: ...

    def disconnect(
        self,
        handler: "NoDataEventListener | None" = None,
    ) -> "typing.Callable[[NoDataEventListener], None] | None":
        """Triggered when the Socket.IO connection is closed.

        Category: `common`


        :param handler: Callback
        :type handler: NoDataEventListener | None
        """
        return self.client.add_on("disconnect", handler=handler, model=None)

    @typing.overload
    def load_history_period_fast(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.LoadHistoryPeriodFastResponse]], None]": ...

    @typing.overload
    def load_history_period_fast(
        self,
        handler: "TypedEventListener[models.LoadHistoryPeriodFastResponse]",
    ) -> None: ...

    def load_history_period_fast(
        self,
        handler: "TypedEventListener[models.LoadHistoryPeriodFastResponse] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.LoadHistoryPeriodFastResponse]], None] | None":
        """Triggered when historical market data for a specific period is loaded.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.LoadHistoryPeriodFastResponse] | None
        """
        return self.client.add_on("loadHistoryPeriodFast", handler=handler, model=models.LoadHistoryPeriodFastResponse)

    @typing.overload
    def success_auth(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessAuthEvent]], None]": ...

    @typing.overload
    def success_auth(
        self,
        handler: "TypedEventListener[models.SuccessAuthEvent]",
    ) -> None: ...

    def success_auth(
        self,
        handler: "TypedEventListener[models.SuccessAuthEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessAuthEvent]], None] | None":
        """Triggered after successful account authorization.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessAuthEvent] | None
        """
        return self.client.add_on("successauth", handler=handler, model=models.SuccessAuthEvent)

    @typing.overload
    def deals_fail_open(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.FailOpenOrderEvent]], None]": ...

    @typing.overload
    def deals_fail_open(
        self,
        handler: "TypedEventListener[models.FailOpenOrderEvent]",
    ) -> None: ...

    def deals_fail_open(
        self,
        handler: "TypedEventListener[models.FailOpenOrderEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.FailOpenOrderEvent]], None] | None":
        """Triggered when a deal fails to open.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.FailOpenOrderEvent] | None
        """
        return self.client.add_on("failopenOrder", handler=handler, model=models.FailOpenOrderEvent)

    @typing.overload
    def deals_success_close(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessCloseDealEvent]], None]": ...

    @typing.overload
    def deals_success_close(
        self,
        handler: "TypedEventListener[models.SuccessCloseDealEvent]",
    ) -> None: ...

    def deals_success_close(
        self,
        handler: "TypedEventListener[models.SuccessCloseDealEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessCloseDealEvent]], None] | None":
        """Triggered after one or more deals are successfully closed.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessCloseDealEvent] | None
        """
        return self.client.add_on("successcloseOrder", handler=handler, model=models.SuccessCloseDealEvent)

    @typing.overload
    def deals_success_open(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.Deal]], None]": ...

    @typing.overload
    def deals_success_open(
        self,
        handler: "TypedEventListener[models.Deal]",
    ) -> None: ...

    def deals_success_open(
        self,
        handler: "TypedEventListener[models.Deal] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.Deal]], None] | None":
        """Triggered after a new deal is successfully opened.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.Deal] | None
        """
        return self.client.add_on("successopenOrder", handler=handler, model=models.Deal)

    @typing.overload
    def deals_update_closed(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None]": ...

    @typing.overload
    def deals_update_closed(
        self,
        handler: "TypedEventListener[list[models.Deal]]",
    ) -> None: ...

    def deals_update_closed(
        self,
        handler: "TypedEventListener[list[models.Deal]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None] | None":
        """Triggered when closed deals information is updated.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.Deal]] | None
        """
        return self.client.add_on("updateClosedDeals", handler=handler, model=models.DealListTypeAdapter)

    @typing.overload
    def deals_update_opened(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None]": ...

    @typing.overload
    def deals_update_opened(
        self,
        handler: "TypedEventListener[list[models.Deal]]",
    ) -> None: ...

    def deals_update_opened(
        self,
        handler: "TypedEventListener[list[models.Deal]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None] | None":
        """Triggered when the list of opened deals is updated.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.Deal]] | None
        """
        return self.client.add_on("updateOpenedDeals", handler=handler, model=models.DealListTypeAdapter)

    @typing.overload
    def price_alert_added(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.PriceAlertAddedEvent]], None]": ...

    @typing.overload
    def price_alert_added(
        self,
        handler: "TypedEventListener[models.PriceAlertAddedEvent]",
    ) -> None: ...

    def price_alert_added(
        self,
        handler: "TypedEventListener[models.PriceAlertAddedEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.PriceAlertAddedEvent]], None] | None":
        """No description

        Category: `ui`


        :param handler: Callback
        :type handler: TypedEventListener[models.PriceAlertAddedEvent] | None
        """
        return self.client.add_on("successprice-alert/add", handler=handler, model=models.PriceAlertAddedEvent)


class PocketOptionClientOnce:
    def __init__(self, client: BasePocketOptionClient) -> None:
        self.client = client

    @typing.overload
    def assets_update(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateAssetItem]]], None]": ...

    @typing.overload
    def assets_update(
        self,
        handler: "TypedEventListener[list[models.UpdateAssetItem]]",
    ) -> None: ...

    def assets_update(
        self,
        handler: "TypedEventListener[list[models.UpdateAssetItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateAssetItem]]], None] | None":
        """Triggered when available trading assets metadata is updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.UpdateAssetItem]] | None
        """
        return self.client.add_on(
            "updateAssets",
            handler=handler,
            model=models.UpdateAssetItemListTypeAdapter,
            once=True,
        )

    @typing.overload
    def change_market_sentiment(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.MarketSentimentItem]]], None]": ...

    @typing.overload
    def change_market_sentiment(
        self,
        handler: "TypedEventListener[list[models.MarketSentimentItem]]",
    ) -> None: ...

    def change_market_sentiment(
        self,
        handler: "TypedEventListener[list[models.MarketSentimentItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.MarketSentimentItem]]], None] | None":
        """Triggered when market sentiment data is updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.MarketSentimentItem]] | None
        """
        return self.client.add_on(
            "chafor",
            handler=handler,
            model=models.MarketSentimentItemListTypeAdapter,
            once=True,
        )

    @typing.overload
    def update_close_value(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateCloseValueItem]]], None]": ...

    @typing.overload
    def update_close_value(
        self,
        handler: "TypedEventListener[list[models.UpdateCloseValueItem]]",
    ) -> None: ...

    def update_close_value(
        self,
        handler: "TypedEventListener[list[models.UpdateCloseValueItem]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.UpdateCloseValueItem]]], None] | None":
        """Triggered when real-time price stream values are updated.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.UpdateCloseValueItem]] | None
        """
        return self.client.add_on(
            "updateStream",
            handler=handler,
            model=models.UpdateCloseValueListTypeAdapter,
            once=True,
        )

    @typing.overload
    def update_history_new_fast(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.UpdateHistoryFastEvent]], None]": ...

    @typing.overload
    def update_history_new_fast(
        self,
        handler: "TypedEventListener[models.UpdateHistoryFastEvent]",
    ) -> None: ...

    def update_history_new_fast(
        self,
        handler: "TypedEventListener[models.UpdateHistoryFastEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.UpdateHistoryFastEvent]], None] | None":
        """Triggered when fast historical market data is received.

        Category: `assets`


        :param handler: Callback
        :type handler: TypedEventListener[models.UpdateHistoryFastEvent] | None
        """
        return self.client.add_on(
            "updateHistoryNewFast",
            handler=handler,
            model=models.UpdateHistoryFastEvent,
            once=True,
        )

    @typing.overload
    def balance_success_update(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessUpdateBalanceEvent]], None]": ...

    @typing.overload
    def balance_success_update(
        self,
        handler: "TypedEventListener[models.SuccessUpdateBalanceEvent]",
    ) -> None: ...

    def balance_success_update(
        self,
        handler: "TypedEventListener[models.SuccessUpdateBalanceEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessUpdateBalanceEvent]], None] | None":
        """Triggered when account balance information is updated.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessUpdateBalanceEvent] | None
        """
        return self.client.add_on(
            "successupdateBalance",
            handler=handler,
            model=models.SuccessUpdateBalanceEvent,
            once=True,
        )

    @typing.overload
    def connect(
        self,
        handler: None = None,
    ) -> "typing.Callable[[NoDataEventListener], None]": ...

    @typing.overload
    def connect(
        self,
        handler: "NoDataEventListener",
    ) -> None: ...

    def connect(
        self,
        handler: "NoDataEventListener | None" = None,
    ) -> "typing.Callable[[NoDataEventListener], None] | None":
        """Triggered when the Socket.IO connection is established.

        Category: `common`


        :param handler: Callback
        :type handler: NoDataEventListener | None
        """
        return self.client.add_on(
            "connect",
            handler=handler,
            model=None,
            once=True,
        )

    @typing.overload
    def disconnect(
        self,
        handler: None = None,
    ) -> "typing.Callable[[NoDataEventListener], None]": ...

    @typing.overload
    def disconnect(
        self,
        handler: "NoDataEventListener",
    ) -> None: ...

    def disconnect(
        self,
        handler: "NoDataEventListener | None" = None,
    ) -> "typing.Callable[[NoDataEventListener], None] | None":
        """Triggered when the Socket.IO connection is closed.

        Category: `common`


        :param handler: Callback
        :type handler: NoDataEventListener | None
        """
        return self.client.add_on(
            "disconnect",
            handler=handler,
            model=None,
            once=True,
        )

    @typing.overload
    def load_history_period_fast(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.LoadHistoryPeriodFastResponse]], None]": ...

    @typing.overload
    def load_history_period_fast(
        self,
        handler: "TypedEventListener[models.LoadHistoryPeriodFastResponse]",
    ) -> None: ...

    def load_history_period_fast(
        self,
        handler: "TypedEventListener[models.LoadHistoryPeriodFastResponse] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.LoadHistoryPeriodFastResponse]], None] | None":
        """Triggered when historical market data for a specific period is loaded.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.LoadHistoryPeriodFastResponse] | None
        """
        return self.client.add_on(
            "loadHistoryPeriodFast",
            handler=handler,
            model=models.LoadHistoryPeriodFastResponse,
            once=True,
        )

    @typing.overload
    def success_auth(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessAuthEvent]], None]": ...

    @typing.overload
    def success_auth(
        self,
        handler: "TypedEventListener[models.SuccessAuthEvent]",
    ) -> None: ...

    def success_auth(
        self,
        handler: "TypedEventListener[models.SuccessAuthEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessAuthEvent]], None] | None":
        """Triggered after successful account authorization.

        Category: `common`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessAuthEvent] | None
        """
        return self.client.add_on(
            "successauth",
            handler=handler,
            model=models.SuccessAuthEvent,
            once=True,
        )

    @typing.overload
    def deals_fail_open(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.FailOpenOrderEvent]], None]": ...

    @typing.overload
    def deals_fail_open(
        self,
        handler: "TypedEventListener[models.FailOpenOrderEvent]",
    ) -> None: ...

    def deals_fail_open(
        self,
        handler: "TypedEventListener[models.FailOpenOrderEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.FailOpenOrderEvent]], None] | None":
        """Triggered when a deal fails to open.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.FailOpenOrderEvent] | None
        """
        return self.client.add_on(
            "failopenOrder",
            handler=handler,
            model=models.FailOpenOrderEvent,
            once=True,
        )

    @typing.overload
    def deals_success_close(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessCloseDealEvent]], None]": ...

    @typing.overload
    def deals_success_close(
        self,
        handler: "TypedEventListener[models.SuccessCloseDealEvent]",
    ) -> None: ...

    def deals_success_close(
        self,
        handler: "TypedEventListener[models.SuccessCloseDealEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.SuccessCloseDealEvent]], None] | None":
        """Triggered after one or more deals are successfully closed.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.SuccessCloseDealEvent] | None
        """
        return self.client.add_on(
            "successcloseOrder",
            handler=handler,
            model=models.SuccessCloseDealEvent,
            once=True,
        )

    @typing.overload
    def deals_success_open(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.Deal]], None]": ...

    @typing.overload
    def deals_success_open(
        self,
        handler: "TypedEventListener[models.Deal]",
    ) -> None: ...

    def deals_success_open(
        self,
        handler: "TypedEventListener[models.Deal] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.Deal]], None] | None":
        """Triggered after a new deal is successfully opened.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[models.Deal] | None
        """
        return self.client.add_on(
            "successopenOrder",
            handler=handler,
            model=models.Deal,
            once=True,
        )

    @typing.overload
    def deals_update_closed(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None]": ...

    @typing.overload
    def deals_update_closed(
        self,
        handler: "TypedEventListener[list[models.Deal]]",
    ) -> None: ...

    def deals_update_closed(
        self,
        handler: "TypedEventListener[list[models.Deal]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None] | None":
        """Triggered when closed deals information is updated.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.Deal]] | None
        """
        return self.client.add_on(
            "updateClosedDeals",
            handler=handler,
            model=models.DealListTypeAdapter,
            once=True,
        )

    @typing.overload
    def deals_update_opened(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None]": ...

    @typing.overload
    def deals_update_opened(
        self,
        handler: "TypedEventListener[list[models.Deal]]",
    ) -> None: ...

    def deals_update_opened(
        self,
        handler: "TypedEventListener[list[models.Deal]] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[list[models.Deal]]], None] | None":
        """Triggered when the list of opened deals is updated.

        Category: `deals`


        :param handler: Callback
        :type handler: TypedEventListener[list[models.Deal]] | None
        """
        return self.client.add_on(
            "updateOpenedDeals",
            handler=handler,
            model=models.DealListTypeAdapter,
            once=True,
        )

    @typing.overload
    def price_alert_added(
        self,
        handler: None = None,
    ) -> "typing.Callable[[TypedEventListener[models.PriceAlertAddedEvent]], None]": ...

    @typing.overload
    def price_alert_added(
        self,
        handler: "TypedEventListener[models.PriceAlertAddedEvent]",
    ) -> None: ...

    def price_alert_added(
        self,
        handler: "TypedEventListener[models.PriceAlertAddedEvent] | None" = None,
    ) -> "typing.Callable[[TypedEventListener[models.PriceAlertAddedEvent]], None] | None":
        """No description

        Category: `ui`


        :param handler: Callback
        :type handler: TypedEventListener[models.PriceAlertAddedEvent] | None
        """
        return self.client.add_on(
            "successprice-alert/add",
            handler=handler,
            model=models.PriceAlertAddedEvent,
            once=True,
        )


class PocketOptionClient(BasePocketOptionClient):
    @property
    def on(self) -> PocketOptionClientOn:
        return PocketOptionClientOn(self)

    @property
    def once(self) -> PocketOptionClientOnce:
        return PocketOptionClientOnce(self)

    @property
    def emit(self) -> PocketOptionClientEmit:
        return PocketOptionClientEmit(self)
